This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./msq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file msq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.acn....done (33 entries accepted, 0 rejected).
Sorting entries....done (186 comparisons).
Generating output file msq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.acr....done (40 lines written, 0 warnings).
Output written in msq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.acr.
Transcript written in msq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.alg.
