This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./psq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file psq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.acn....done (59 entries accepted, 0 rejected).
Sorting entries....done (351 comparisons).
Generating output file psq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.acr....done (62 lines written, 0 warnings).
Output written in psq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.acr.
Transcript written in psq19_Bousbiat_Hafsa_Ihadadene_Sana_SIQ.alg.
