This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./Report_backup.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Report_backup.acn....done (33 entries accepted, 0 rejected).
Sorting entries....done (186 comparisons).
Generating output file Report_backup.acr....done (40 lines written, 0 warnings).
Output written in Report_backup.acr.
Transcript written in Report_backup.alg.
